//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gaming.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Hero
    {
        public int Hero_ID { get; set; }
        public int Owner_ID { get; set; }
        [Required]
        public string Nickname { get; set; }
        [Required]
        [Range(1, 100)]
        public int Level { get; set; }
        public string Class { get; set; }
        public Nullable<int> Equipment { get; set; }
        public Nullable<int> Guild { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Equipment Equipment1 { get; set; }
        public virtual Guild Guild1 { get; set; }
    }
}
