//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gaming.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Quest
    {
        public int Quest_ID { get; set; }
        [Required]
        public string Name { get; set; }
        [Range(1, 100)]
        public int Level_required { get; set; }
        public Nullable<int> Reward_eq { get; set; }
        [Required]
        public int NPC_giving { get; set; }
        public Nullable<int> Event_ID { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Event Event { get; set; }
        public virtual NPC NPC { get; set; }
    }
}
