//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gaming.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raid
    {
        public int Raid_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Level_required { get; set; }
        public int Boss { get; set; }
        public Nullable<int> Event_ID { get; set; }
    
        public virtual Boss Boss1 { get; set; }
        public virtual Event Event { get; set; }
    }
}
